name: Deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    types: [ "closed" ]

env:
  PROJECT_NAME: ajouevent-fe
  BUCKET_NAME: ajouevent-cicd
  CODE_DEPLOY_APP_NAME: ajouevent-fe
  DEPLOYMENT_GROUP_NAME: ajouevent-fe

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Check Node v
        run: node -v

      - name: Install Dependencies
        run: npm install

      - name: .env
        run: echo "${{secrets.ENV}}" > ./.env

      - name: Build
        run: npm run build
        env:
          CI : ""

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment
          --application-name $CODE_DEPLOY_APP_NAME
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name $DEPLOYMENT_GROUP_NAME
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip